# Generated by Django 4.2.4 on 2023-08-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=70)),
                ('prenom', models.CharField(max_length=70)),
               
                ('age', models.CharField(max_length=70)),
                ('nature', models.CharField(max_length=70)),
                ('date', models.CharField(max_length=70)),
                ('duree', models.CharField(max_length=70)),
                ('superviseur', models.CharField(max_length=70)),
            ],
        ),
    ]
