# Generated by Django 4.2.4 on 2023-08-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0004_encadrant_alter_user_age_alter_user_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encadrant',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
