# Generated by Django 4.2.4 on 2023-08-23 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0005_alter_encadrant_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='encadrant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myweb.encadrant'),
        ),
        migrations.AlterField(
            model_name='encadrant',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
