# Generated by Django 4.2.4 on 2023-08-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0006_user_encadrant_alter_encadrant_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='encadrant',
            name='nb_stagiaires_supervises',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
