# Generated by Django 4.2.4 on 2023-08-28 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0007_encadrant_nb_stagiaires_supervises'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sujet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('encadrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.encadrant')),
                ('stagiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.user')),
            ],
        ),
    ]
