# Generated by Django 4.2.4 on 2023-08-28 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0008_sujet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sujet',
            name='encadrant',
        ),
        migrations.RemoveField(
            model_name='sujet',
            name='stagiaire',
        ),
        migrations.AddField(
            model_name='encadrant',
            name='sujet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myweb.sujet'),
        ),
    ]
