# Generated by Django 4.2.4 on 2023-08-28 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0009_remove_sujet_encadrant_remove_sujet_stagiaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sujet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myweb.sujet'),
        ),
    ]
