# Generated by Django 4.2.4 on 2023-08-28 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0010_user_sujet'),
    ]

    operations = [
        migrations.AddField(
            model_name='sujet',
            name='stagiaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sujets_affectes', to='myweb.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='encadrant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stagiaires_encadres', to='myweb.encadrant'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sujet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sujets_associes', to='myweb.sujet'),
        ),
    ]
