# Generated by Django 4.2.4 on 2023-08-28 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0011_sujet_stagiaire_alter_user_encadrant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sujet',
            name='stagiaire',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sujet_attribue', to='myweb.user'),
        ),
    ]
