# Generated by Django 4.2.4 on 2023-08-28 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0012_alter_sujet_stagiaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sujet',
            name='stagiaire',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sujet_associé', to='myweb.user'),
        ),
    ]
