# Generated by Django 4.2.4 on 2023-08-28 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0014_alter_user_duree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='encadrant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stagiaires_encadres', to='myweb.user'),
        ),
    ]
