# Generated by Django 4.2.4 on 2023-08-28 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0015_alter_user_encadrant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='encadrant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stagiaires_encadres', to='myweb.encadrant'),
        ),
    ]
