# Generated by Django 4.2.4 on 2023-08-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0017_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='RH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('departement', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('mot_de_passe_rh', models.CharField(max_length=128)),
            ],
        ),
    ]
