# Generated by Django 4.2.4 on 2023-08-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0018_rh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rh',
            name='mot_de_passe_rh',
            field=models.CharField(max_length=128, verbose_name='Mot de passe'),
        ),
    ]
