# Generated by Django 4.2.4 on 2023-08-31 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0019_alter_rh_mot_de_passe_rh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rh',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='rh',
            name='mot_de_passe_rh',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='rh',
            name='telephone',
            field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('description', models.TextField()),
                ('sujet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.sujet')),
            ],
        ),
    ]
