# Generated by Django 4.2.4 on 2023-09-01 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0020_alter_rh_email_alter_rh_mot_de_passe_rh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='sujet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='myweb.sujet'),
        ),
    ]
