# Generated by Django 4.2.4 on 2023-09-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0021_alter_tache_sujet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='fichier_pdf',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
