# Generated by Django 4.2.4 on 2023-09-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0022_tache_fichier_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rh',
            name='mot_de_passe_rh',
        ),
        migrations.AddField(
            model_name='rh',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rh',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rh',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='rh',
            name='password',
            field=models.CharField(default='1', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rh',
            name='telephone',
            field=models.CharField(max_length=20),
        ),
    ]
