# Generated by Django 4.2.4 on 2023-09-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0023_remove_rh_mot_de_passe_rh_rh_is_active_rh_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encadrant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='encadrant',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='encadrant',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='encadrant',
            name='password',
            field=models.CharField(default='sef', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
